name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        ghc-version: ["9.4.8"]
        cabal: [ '3.10.3.0' ]
    steps:
      - name: Install gcc
        shell: bash
        run: |
          brew install gcc
          GCC="$(brew --prefix)/bin/gcc"
          GXX="$(brew --prefix)/bin/g++"
          echo "GCC=$GCC" >> $GITHUB_ENV
          echo "GXX=$GXX" >> $GITHUB_ENV

      - name: Install LLVM 15
        shell: bash
        run: |
          brew install llvm@15
          LD_LLD="$(brew --prefix llvm@15)/bin/ld.lld"
          echo "LD_LLD=$LD_LLD" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal }}

      - name: sed hackery
        shell: bash
        run: |
          sed -i.bak -E "s|(\(\"C\ compiler\ command\",\ \")[^\"]*(\"\))|\1${GCC}\2|" $(ghc --print-libdir)/settings
          sed -i.bak -E "s|(\(\"C\+\+\ compiler\ command\",\ \")[^\"]*(\"\))|\1${GXX}\2|" $(ghc --print-libdir)/settings
          # Pass `-fuse-ld=lld` to gcc when linking.
          sed -i.bak -E "s|(\(\"C\ compiler\ link\ flags\",\ \")[^\"]*(\"\))|\1-fuse-ld=lld\2|" $(ghc --print-libdir)/settings
          # Remove C/C++ compiler flags which gcc doesn't understand (namely,
          # `--target=arm64-apple-darwin`).
          sed -i.bak -E "s|(\(\"C\ compiler\ flags\",\ \")[^\"]*(\"\))|\1\2|" $(ghc --print-libdir)/settings
          sed -i.bak -E "s|(\(\"C\+\+\ compiler\ flags\",\ \")[^\"]*(\"\))|\1\2|" $(ghc --print-libdir)/settings
          # Switch the linker used for merging objects from Apple's ld to LLVM's
          # ld.lld.
          sed -i.bak -E "s|(\(\"Merge\ objects\ command\",\ \")[^\"]*(\"\))|\1${LD_LLD}\2|" $(ghc --print-libdir)/settings

      - shell: bash
        run: ghc --info

      - name: Build
        shell: bash
        run: cabal build
