name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        ghc-version: ["9.4.8"]
        cabal: [ '3.10.3.0' ]
    steps:
      - name: Try linkers
        shell: bash
        run: |
          ls /opt/homebrew/bin || true
          /opt/homebrew/bin/lld --version || true
          /opt/homebrew/bin/ld.lld --version || true

      # - uses: actions/checkout@v2
      #   with:
      #     submodules: true

      # - uses: haskell-actions/setup@v2
      #   id: setup-haskell
      #   with:
      #     ghc-version: ${{ matrix.ghc-version }}
      #     cabal-version: ${{ matrix.cabal }}

      # - shell: bash
      #   run: ghc --info
