name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check environment variables
        shell: bash
        run: |
          echo $LANG
          echo $LC_ALL
