name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Test
        shell: bash
        run: |
          echo "Hello, World"
