name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        ghc-version: ["9.4.8"]
        cabal: [ '3.10.3.0' ]
    steps:
      - name: Install LLVM 15
        shell: bash
        run: |
          curl -sSL https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/clang+llvm-15.0.7-arm64-apple-darwin22.0.tar.xz -o llvm.tar.xz && tar xf llvm.tar.xz && mv clang+llvm-* llvm
          LD="$PWD/llvm/bin/ld.lld"
          echo "LD=$LD" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal }}

      - name: sed hackery
        shell: bash
        run: sed -i '' 's/("Merge objects command", "ld.lld")/("Merge objects command", "ld")/' $(ghc --print-libdir)/settings

      - shell: bash
        run: ghc --info

      - name: Build
        shell: bash
        run: cabal build
