name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Compile executable
        shell: bash
        run: clang test.c -o test

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_P12_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_P12_PASSWORD }}

      - name: Sign binary
        env:
          IDENTITY_NAME: ${{ secrets.APPLE_P12_IDENTITY_NAME }}
        run: |
          codesign \
            --deep --force --options runtime \
            --sign "$IDENTITY_NAME" \
            test

      - name: Zip binary
        run: |
          zip test.zip test

      - name: Notarize and staple
        env:
          KEY_ID: ${{ secrets.APPLE_P8_KEY_ID }}
          ISSUER_ID: ${{ secrets.APPLE_P8_ISSUER_ID }}
          API_KEY: ${{ secrets.APPLE_P8_API_KEY }}
        run: |
          echo "$API_KEY" > "AuthKey_$KEY_ID.p8"
          xcrun notarytool submit test.zip \
            --key "AuthKey_$KEY_ID.p8" \
            --key-id "$KEY_ID" \
            --issuer "$ISSUER_ID" \
            --wait
          xcrun stapler staple test

      - name: Upload executable
        uses: actions/upload-artifact@v6
        with:
          name: test
          path: "test"
          if-no-files-found: error
          retention-days: 1
