name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Clang/LLVM 14
        shell: bash
        run: |
          brew install llvm@14
          echo "$(brew --prefix)/opt/llvm@12/bin" >> "$GITHUB_PATH"

      - name: Clang version
        shell: bash
        run: clang --version

      - name: Compile simple C file
        shell: bash
        run: clang test.c
