name: gha-sandbox

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Clang/LLVM 12
        shell: bash
        run: |
          brew install llvm@12
          echo "$(brew --prefix)/opt/llvm@12/bin" >> "$GITHUB_PATH"
          echo "CPATH=$(brew --prefix)/include" >> "$GITHUB_ENV"
          echo "LIBRARY_PATH=$(brew --prefix)/lib" >> "$GITHUB_ENV"

      - name: Clang version
        shell: bash
        run: clang --version

      - name: Compile simple C file
        shell: bash
        run: clang test.c
