name: GHA-Sandbox
on:
  - push
  - pull_request
jobs:
  windows:
    name: Windows Python test
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          path-type: inherit
          install: |
            mingw-w64-x86_64-gcc

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Debugging (msys2)
        shell: msys2 {0}
        run: |
          echo $PATH
          ls $pythonLocation
          type -a python
          python --version
          type -a python3
          python3 --version
          type -a cmake
          cmake --version
          type -a gcc
          ls /c/hostedtoolcache/windows/Python/3.10.10/x86
          gcc --version
          gcc -Wl,--version
          gcc -fuse-ld=gold -Wl,--version
