name: GHA-Sandbox
on:
  - push
  - pull_request
jobs:
  windows:
    name: Linux flex test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debugging (msys2)
        shell: bash
        run: |
          flex --version
          ls /usr/bin
          ls /usr/include
