name: GHA-Sandbox
on:
  - push
  - pull_request
jobs:
  windows:
    name: Windows Python test
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          path-type: inherit

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Debugging (msys2)
        shell: msys2 {0}
        run: |
          echo $PATH
          ls $pythonLocation
          which -a python
          which -a python3
          type -a python
          type -a python3

      - name: Debugging (bash)
        shell: bash
        run: |
          echo $PATH
          ls $pythonLocation
          which -a python
          which -a python3
          type -a python
          type -a python3
