name: GHA-Sandbox
on:
  - push
  - pull_request
jobs:
  linux:
    name: install-nix-action with ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-20.04
          - runs-on: ubuntu-22.04
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:21.11
          install_url: https://releases.nixos.org/nix/nix-2.10.3/install

      - name: Test nix shell
        run: |
          nix shell nixpkgs#gmp -c ls
